# .travis.yml
os: linux
language: php

cache:
  directories:
    - $HOME/.composer/cache
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache
    - vendor
php:
  - 7.1

before_script:
  - composer self-update --stable -n

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest 

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=build/logs/clover.xml
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml

notifications:
  email: false